/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package treevisualization;

//import com.formdev.flatlaf.FlatDarkLaf;

import trees.BST;
import edu.princeton.cs.algs4.StdRandom;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;

/**
 * The main class, responsible for displaying the graphical interface 
 * according to the selected tree.
 *
 * @author Emerson
 * @since 06/2021
 */
public class ASTViewer extends javax.swing.JFrame {
    private BST tree;
    
    /**
     * Creates new form JanelaVisualizacaoArvore
     */
    public ASTViewer() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AST Viewer");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btnBST.setBackground(new java.awt.Color(204, 204, 204));
        btnBST.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnBST.setForeground(new java.awt.Color(51, 51, 51));
        btnBST.setText("Binary Search Tree");
        btnBST.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnBST)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBST)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSTActionPerformed
        
        tree = new BST();
        
        try{
            
            insertElements();
            
            PrintWriter pw = new PrintWriter( new File( "ast.xml" ) );
            tree.visitRoot(tree.getRoot());
            pw.write(tree.getXMLArvore());
            pw.close();
            
            new JDTreeView( this, true ).setVisible( true );
            
            tree = new BST();
            
        }catch(FileNotFoundException fl){
            System.out.println( fl.getMessage() );
        } 
        
    }//GEN-LAST:event_btnBSTActionPerformed
    
    /**
     * This method generates a random string [].
     */
    private void insertElements(){
        String[] element = "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
                .split(" ");
        
        int i = 0;
        
        do{
            int aux = StdRandom.uniform( element.length );
            
            if( tree.get(element[aux]) == null ){
                tree.put( element[aux], aux );
                i++;
            }
            
        }while( i < 10 );
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        
        //FlatDarkLaf.install();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASTViewer().setVisible( true );
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBST;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
