/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package treevisualization;

//import com.formdev.flatlaf.FlatDarkLaf;

import trees.BST;
import edu.princeton.cs.algs4.StdRandom;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;

/**
 *
 * @author Emerson
 */
public class ASTViewer extends javax.swing.JFrame {
    private BST tree;
    
    /**
     * Creates new form JanelaVisualizacaoArvore
     */
    public ASTViewer() {
        initComponents();
        tree = new BST();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AST Viewer");

        btnBST.setText("Binary Search Tree");
        btnBST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnBST)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBST)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSTActionPerformed
        
        try{
            
            insertElements();
            
            PrintWriter pw = new PrintWriter( new File( "ast.xml" ) );
            tree.visitRoot(tree.getRoot());
            pw.write(tree.getXMLArvore());
            pw.close();
            
            new JDTreeView( this, true ).setVisible( true );
            
            tree = new BST();
            
        }catch(FileNotFoundException fl){
            System.out.println( fl.getMessage() );
        } 
        
    }//GEN-LAST:event_btnBSTActionPerformed
    
    private void insertElements(){
        String[] element = "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
                .split(" ");
        
        int i = 0;
        
        do{
            int aux = StdRandom.uniform( element.length );
            
            if( tree.get(element[aux]) == null ){
                tree.put( element[aux], aux );
                i++;
            }
            
        }while( i < 10 );
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        
        //FlatDarkLaf.install();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASTViewer().setVisible( true );
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBST;
    // End of variables declaration//GEN-END:variables
}
